module.exports = {
modul: {
	axios: require('axios'),
	boom: require('@hapi/boom'),
	baileys: require("@whiskeysockets/baileys"),
	chalk: require('chalk'),
	crypto: require('crypto'),
	cheerio: require('cheerio'),
	child_process: require('child_process'),
	process: require('process'),
	cookie: require('cookie'),
	fs: require('fs'),
	fsx: require('fs-extra'),
	pino: require('pino'),
	fetch: require('node-fetch'),
	figlet: require('figlet'),
	FormData: require('form-data'),
	FileType: require('file-type'),
	keyeddb: require('@adiwajshing/keyed-db'),
	qs: require('qs'),
  qrcodeterminal: require('qrcode-terminal'),
  qrcode: require('qrcode'),
  request: require('request'),
  moment: require('moment-timezone'),
  ms: require('ms'),
  syntaxerror: require('syntax-error'),
  speed: require('performance-now'),
  util: require('util')
}
}